title: "Associação Espírita Pai Kachambí"
description: "Associação Espírita Pai Kachambí - Escalas"
keywords: "kachambi, umbanda, escalas, desenvolvimento mediunico, mediunidade, preto-velho"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# https://github.com/avillafiorita/jekyll-datapage_gen
page_gen-dirs: true
page_gen:
  - data: "escalas"
    template: "escalas"
    "dir": ""
    "name": "id"
  - data: "escalas"
    template: "escalas_impressao"
    "dir": "impressao"
    "name": "id"

plugins:
  - jekyll-datapage-generator

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - LICENSE
  - tailwind.config.js
